categories = [
  'Adventure Travel',
  'Artistic Expressions',
  'Breaking Stereotypes',
  'Celebrating Diversity',
  'Community Building',
  'Culinary Adventures',
  'DIY and Maker Culture',
  'Educational Breakthroughs',
  'Environmental Activism',
  'Equality and Diversity',
  'Fashion Forward',
  'Film and Cinema Evolution',
  'Future of Work',
  'Global Innovations',
  'Historical Reinterpretations',
  'Humanitarian Efforts',
  'Inclusive Technology',
  'Innovative Tech Trends',
  'Inspirational Leadership',
  'Intersectional Feminism',
  'Literary Gems',
  'Mindfulness and Meditation',
  'Music Beyond Genres',
  'Personal Development Journeys',
  'Positive News and Stories',
  'Queer Art and Culture',
  'Scientific Discoveries',
  'Social Justice Initiatives',
  'Space Exploration',
  'Sports Beyond Boundaries',
  'Sustainable Living',
  'Transgender Voices',
  'Unconventional Wisdom',
  'Wellness and Mental Health',
  'Women Empowerment',
  'Women in Leadership',
  'Women in STEM',
  'Women\'s Achievements in Sports',
  'Women\'s Contributions to Arts',
  'Women\'s Empowerment Stories',
  'Women\'s Health and Wellness',
]

categories.each do |category|
  Category.create(name: category)
end
